using System.Collections.Generic;
using Cysharp.Threading.Tasks;
using DG.Tweening;
using Sirenix.OdinInspector;
using StampJourney.Core;
using StampJourney.Gameplay;
using TMPro;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.Rendering;

namespace StampJourney.Card
{
    /// <summary>
    /// View + Input handler for each card.
    /// Uses EventSystem pointer input with a Physics2DRaycaster for mouse and touch.
    /// When dragging a group: moves the permanent parent transform; scales/tilts during drag.
    /// </summary>
    [RequireComponent(typeof(BoxCollider2D))]
    public class CardView : MonoBehaviour,
        IPointerDownHandler,
        IDragHandler,
        IPointerUpHandler
    {
        #region Inspector — Visuals

        [BoxGroup("Visuals")]
        [Required] public SpriteRenderer contentImg;
        [BoxGroup("Visuals")]
        public SpriteRenderer glowImg;
        [BoxGroup("Visuals")]
        public GameObject pressEffect;
        [BoxGroup("Visuals")]
        public SpriteRenderer backGroundImg;
        [BoxGroup("Visuals")]
        public CardEdgeRenderer cardEdgeRenderer;
        [BoxGroup("Visuals")]
        public SortingGroup sortingGroup;

        [BoxGroup("Ice Obstacle")]
        [Tooltip("Optional authored ice overlay. A fallback overlay is created at runtime when empty.")]
        public SpriteRenderer iceOverlay;
        [BoxGroup("Ice Obstacle")]
        [Tooltip("Optional authored counter label. A fallback label is created at runtime when empty.")]
        public TMP_Text iceCountText;

        #endregion

        #region Inspector — Settings

        [BoxGroup("Settings")]
        public float liftScale = 1.05f;
        [BoxGroup("Settings")]
        public float liftDuration = 0.12f;
        [BoxGroup("Settings")]
        public float snapDuration = 0.18f;
        [BoxGroup("Settings")]
        public int baseSortingOrder = 10;
        [BoxGroup("Settings")]
        public int dragSortingOrder = 100;

        public int completeSortingOrder = 50;

        [BoxGroup("Link State Colors")]
        [LabelText("1 Item - Blue")]
        public Color oneItemColor = new Color32(77, 157, 224, 255);

        [BoxGroup("Link State Colors")]
        [LabelText("2 Items - Green")]
        public Color twoItemColor = new Color32(91, 203, 119, 255);

        [BoxGroup("Link State Colors")]
        [LabelText("3 Items - Orange")]
        public Color threeItemColor = new Color32(255, 159, 67, 255);

        [BoxGroup("Link State Colors")]
        [LabelText("4 Items - Purple")]
        public Color fourItemColor = new Color32(155, 93, 229, 255);

        [BoxGroup("Link State Colors")]
        [MinValue(0f)]
        public float linkColorTweenDuration = 0.24f;

        #endregion

        #region Inspector — Drag Effects

        [BoxGroup("Drag Effects")]
        [LabelText("Follow Speed")]
        [Tooltip("How quickly the card follows the pointer. Higher values feel tighter.")]
        [MinValue(1f)]
        public float dragFollowSpeed = 30f;

        [BoxGroup("Drag Effects")]
        [LabelText("Max Tilt Angle")]
        [Tooltip("Maximum tilt angle when dragging horizontally (degrees)")]
        public float maxTiltAngle = 32f;

        [BoxGroup("Drag Effects")]
        [LabelText("Tilt Smoothing")]
        [Tooltip("Lerp speed of tilt angle (higher = more responsive)")]
        public float tiltSmoothing = 20f;

        [BoxGroup("Drag Effects")]
        [LabelText("Tilt From Speed")]
        [Tooltip("Amount of tilt generated by horizontal drag speed.")]
        [MinValue(0f)]
        public float tiltVelocityScale = 0.45f;

        #endregion

        #region Constants

        private const float FlipDuration = 0.4f;
        private const float RippleScaleUp = 1.35f;
        private const float RippleScaleUpDuration = 0.18f;
        private const float RippleScaleDownDuration = 0.2f;
        private const int NoPointer = int.MinValue;

        #endregion

        #region Runtime State

        [ShowInInspector] private CardModel _model;
        private Gameboard _board;
        private bool _isDragging;
        private bool _isSnapping;
        private bool _releaseInProgress;
        private Camera _mainCamera;
        private int _activePointerId = NoPointer;
        private static CardView _activeDragView;

        // Drag state
        private Vector2 _originPos;
        private Vector3 _dragOffset;
        private CardGroup _dragGroup;
        private Vector3 _prevDragPos;
        private Vector3 _dragTargetPosition;
        private float _currentTilt;
        private int _currentLinkedItemCount = -1;
        private Tween _backgroundColorTween;

        // Group drag state
        private Vector2 _groupDragOriginPos;

        #endregion

        #region Properties

        public CardModel Model => _model;

        #endregion

        #region Initialization

        public void Init(CardModel model, Gameboard board)
        {
            _backgroundColorTween?.Kill();
            _currentLinkedItemCount = -1;
            _model = model;
            _board = board;
            _mainCamera = Camera.main;

            _originPos = transform.position;
            SetSortingOrder(baseSortingOrder);
            EnsureIceVisuals();
            RefreshVisual();

            if (cardEdgeRenderer != null)
                cardEdgeRenderer.Init(model, board);
        }

        public void RefreshVisual()
        {
            if (_model == null) return;
            if (_model.HasAssignedContent)
                SetLinkedItemCount(_model.Group?.Count ?? 1, false);
            else if (backGroundImg != null)
                backGroundImg.color = Color.white;
            contentImg.sprite = _model.HasAssignedContent
                ? _model.Topic.GetItemSprite(_model.ItemIndex)
                : null;
            contentImg.color = Color.white;
            pressEffect.SetActive(false);
            if (contentImg.sprite != null)
                FitSpriteContent(1, 1);
            RefreshIceVisual(false);
        }

        public void RefreshIceVisual(bool animate)
        {
            EnsureIceVisuals();
            bool showIce = _model != null && _model.IsIced;

            if (iceCountText != null)
            {
                iceCountText.text = showIce ? _model.IceCount.ToString() : string.Empty;
                iceCountText.gameObject.SetActive(showIce);
            }

            if (iceOverlay == null) return;
            iceOverlay.DOKill();

            if (!showIce)
            {
                if (animate && iceOverlay.gameObject.activeSelf)
                {
                    iceOverlay.DOFade(0f, 0.2f).SetEase(Ease.OutQuad).OnComplete(() =>
                    {
                        if (iceOverlay != null)
                            iceOverlay.gameObject.SetActive(false);
                    });
                }
                else
                {
                    iceOverlay.gameObject.SetActive(false);
                }
                return;
            }

            iceOverlay.gameObject.SetActive(true);
            Color iceColor = iceOverlay.color;
            iceColor.a = 0.72f;
            iceOverlay.color = iceColor;
            if (animate)
                iceOverlay.transform.DOPunchScale(Vector3.one * 0.08f, 0.22f, 5, 0.5f);
        }

        private void EnsureIceVisuals()
        {
            if (iceOverlay == null)
            {
                var overlayObject = new GameObject("Ice Overlay");
                overlayObject.transform.SetParent(transform, false);
                iceOverlay = overlayObject.AddComponent<SpriteRenderer>();
                if (backGroundImg != null)
                {
                    iceOverlay.sprite = backGroundImg.sprite;
                    iceOverlay.drawMode = backGroundImg.drawMode;
                    iceOverlay.size = backGroundImg.size;
                    iceOverlay.sortingLayerID = backGroundImg.sortingLayerID;
                    iceOverlay.sortingOrder = backGroundImg.sortingOrder + 20;
                }
                iceOverlay.color = new Color(0.55f, 0.9f, 1f, 0.72f);
            }

            if (iceCountText == null)
            {
                var textObject = new GameObject("Ice Count");
                textObject.transform.SetParent(transform, false);
                textObject.transform.localPosition = new Vector3(0f, 0f, -0.05f);
                var label = textObject.AddComponent<TextMeshPro>();
                label.alignment = TextAlignmentOptions.Center;
                label.fontSize = 4f;
                label.fontStyle = FontStyles.Bold;
                label.color = new Color(0.03f, 0.2f, 0.35f, 1f);
                label.rectTransform.sizeDelta = Vector2.one;
                label.renderer.sortingLayerID = iceOverlay.sortingLayerID;
                label.renderer.sortingOrder = iceOverlay.sortingOrder + 1;
                iceCountText = label;
            }
        }

        #endregion

        #region Link State Color

        /// <summary>
        /// Updates this card's background from the number of linked topic items.
        /// The bridge receives every tweened color so the connected shape stays unified.
        /// </summary>
        public void SetLinkedItemCount(int linkedItemCount, bool animate)
        {
            if (_model == null || !_model.HasAssignedContent || backGroundImg == null) return;

            int clampedCount = Mathf.Clamp(linkedItemCount, 1, 4);
            Color targetColor = GetLinkStateColor(clampedCount);
            if (_currentLinkedItemCount == clampedCount &&
                Approximately(backGroundImg.color, targetColor))
                return;

            _currentLinkedItemCount = clampedCount;
            _backgroundColorTween?.Kill();
            cardEdgeRenderer?.SetLiquidColor(backGroundImg.color);

            if (!animate || linkColorTweenDuration <= 0f)
            {
                backGroundImg.color = targetColor;
                cardEdgeRenderer?.SetLiquidColor(targetColor);
                return;
            }

            _backgroundColorTween = backGroundImg
                .DOColor(targetColor, linkColorTweenDuration)
                .SetEase(Ease.InOutSine)
                .OnUpdate(() => cardEdgeRenderer?.SetLiquidColor(backGroundImg.color))
                .OnComplete(() =>
                {
                    backGroundImg.color = targetColor;
                    cardEdgeRenderer?.SetLiquidColor(targetColor);
                    _backgroundColorTween = null;
                });
        }

        public Color GetLinkStateColor(int linkedItemCount)
        {
            return Mathf.Clamp(linkedItemCount, 1, 4) switch
            {
                2 => twoItemColor,
                3 => threeItemColor,
                4 => fourItemColor,
                _ => oneItemColor
            };
        }

        private static bool Approximately(Color a, Color b)
        {
            const float tolerance = 0.001f;
            return Mathf.Abs(a.r - b.r) < tolerance &&
                   Mathf.Abs(a.g - b.g) < tolerance &&
                   Mathf.Abs(a.b - b.b) < tolerance &&
                   Mathf.Abs(a.a - b.a) < tolerance;
        }

        #endregion

        #region Flip Animation

        public void PlayFlip(FlipState targetState, bool instantly = true)
        {
            if (_model == null) return;
            _model.FlipState = targetState;

            float targetY = targetState == FlipState.Up ? 0f : 180f;
            bool showContent = targetState == FlipState.Up;

            if (instantly)
            {
                transform.localEulerAngles = new Vector3(0f, targetY, 0f);
                if (contentImg != null) contentImg.gameObject.SetActive(showContent);
            }
            else
            {
                transform.DORotate(new Vector3(0f, targetY, 0f), FlipDuration).SetEase(Ease.InOutSine);
                DOVirtual.DelayedCall(FlipDuration / 2f, () =>
                {
                    if (contentImg != null) contentImg.gameObject.SetActive(showContent);
                });
            }
        }

        #endregion

        #region Sorting

        public void SetSortingOrder(int targetOrder)
        {
            if (sortingGroup == null)
            {
                AndyUtil.Logger.LogError("[CardView] sortingGroup is null", this);
                return;
            }
            sortingGroup.sortingOrder = targetOrder;
            cardEdgeRenderer?.SetLiquidBridgeSortingOrder(targetOrder);
        }

        #endregion

        #region Sprite Fitting

        public void FitSpriteContent(float maxWidth, float maxHeight)
        {
            Vector2 spriteSize = contentImg.sprite.bounds.size;
            float scaleX = maxWidth / spriteSize.x;
            float scaleY = maxHeight / spriteSize.y;
            var targetScale = Mathf.Min(scaleX, scaleY) * 0.85f;

            contentImg.transform.localScale = new Vector3(targetScale, targetScale, 1f);
        }

        #endregion

        #region Drag & Drop

        public void OnPointerDown(PointerEventData eventData)
        {
            if (eventData.button != PointerEventData.InputButton.Left) return;
            if (_activeDragView != null && _activeDragView != this) return;
            // Iced cards are locked obstacles: they cannot initiate a drag or swap.
            if (_model == null || _model.IsIced || _model.IsAnimating || _isSnapping || !_model.CanDrag || _model.FlipState == FlipState.Down) return;
            if (_model.Group != null && _model.Group.IsTopicComplete) return;

            // A targeted booster gets first use of the card press. While a booster is executing,
            // the controller also consumes presses so drag logic cannot mutate the same board.
            if (_board != null && _board.Boosters != null &&
                _board.Boosters.HandleCardPressed(_model))
                return;

            if (_model.Group != null && _model.Group.HasCardAnimating) return;
            if (GameManager.Instance.State != GameState.Playing) return;

            // Block drag if this column has cards currently dropping
            if (_board != null && _board.IsColumnBusy(_model.BoardCol)) return;

            // Force-complete any running DOMove tweens to prevent position glitches
            // when quick-dragging before a previous swap animation finishes.
            ForceCompletePendingTweens();

            _isDragging = true;
            _activePointerId = eventData.pointerId;
            _activeDragView = this;
            _dragGroup = _model.Group;
            _originPos = transform.position;
            _currentTilt = 0f;

            Vector3 pointerWorldPosition = ScreenToWorld(eventData.position);

            if (_dragGroup != null && _dragGroup.Count > 1 && _dragGroup.GroupTransform != null)
                BeginGroupDrag(pointerWorldPosition);
            else
                BeginSingleDrag(pointerWorldPosition);

            Transform dragTransform = GetDragTransform();
            _dragTargetPosition = dragTransform.position;
            _prevDragPos = dragTransform.position;

            if (glowImg) glowImg.DOFade(1f, liftDuration);
            if (_dragGroup != null && _dragGroup.Count > 1)
                SetGroupPressEffects(true);
            else if (pressEffect)
                pressEffect.SetActive(true);
        }

        public void OnDrag(PointerEventData eventData)
        {
            if (eventData.pointerId != _activePointerId) return;
            if (!_isDragging || _isSnapping) return;
            if (_model.Group != null && _model.Group.HasCardAnimating) return;
            _dragTargetPosition = ScreenToWorld(eventData.position) + _dragOffset;
        }

        public void OnPointerUp(PointerEventData eventData)
        {
            if (eventData.pointerId != _activePointerId) return;
            _activePointerId = NoPointer;
            ReleaseDragAsync().Forget();
        }

        private void LateUpdate()
        {
            if (!_isDragging || _isSnapping) return;

            Transform dragTransform = GetDragTransform();
            float deltaTime = Time.unscaledDeltaTime;
            if (deltaTime <= 0f) return;

            // Exponential damping gives the same follow feel at 30, 60 and 120 FPS.
            float followAmount = 1f - Mathf.Exp(-dragFollowSpeed * deltaTime);
            Vector3 newPosition = Vector3.Lerp(
                dragTransform.position,
                _dragTargetPosition,
                followAmount);
            float velocityX = (newPosition.x - _prevDragPos.x) / deltaTime;
            float targetTilt = Mathf.Clamp(
                -velocityX * tiltVelocityScale,
                -maxTiltAngle,
                maxTiltAngle);
            float tiltAmount = 1f - Mathf.Exp(-tiltSmoothing * deltaTime);

            _currentTilt = Mathf.Lerp(_currentTilt, targetTilt, tiltAmount);
            dragTransform.position = newPosition;
            dragTransform.rotation = Quaternion.Euler(0f, 0f, _currentTilt);
            _prevDragPos = newPosition;
        }

        private void OnApplicationFocus(bool hasFocus)
        {
            if (!hasFocus && _isDragging)
                ReleaseDragAsync().Forget();
        }

        private async UniTask ReleaseDragAsync()
        {
            if (!_isDragging || _releaseInProgress) return;

            _releaseInProgress = true;
            _isDragging = false;
            _activePointerId = NoPointer;

            if (glowImg) glowImg.DOFade(0f, snapDuration);
            if (_dragGroup != null && _dragGroup.Count > 1)
                SetGroupPressEffects(false);
            else if (pressEffect)
                pressEffect.SetActive(false);

            _currentTilt = 0f;

            try
            {
                if (_dragGroup != null && _dragGroup.Count > 1 && _dragGroup.GroupTransform != null)
                    await HandleGroupRelease();
                else
                    await HandleSingleRelease();
            }
            catch (System.Exception exception)
            {
                // A UI/event subscriber runs inside the awaited board settlement path. Its
                // failure must not leave this card permanently in a dragged/snapping state.
                Debug.LogException(exception, this);
            }
            finally
            {
                _isDragging = false;
                _isSnapping = false;
                _releaseInProgress = false;
                _currentTilt = 0f;
                if (_activeDragView == this)
                    _activeDragView = null;
            }
        }

        #endregion

        #region Swap Logic

        private async UniTask DoSingleGridSwapAsync(Vector2Int gridDelta)
        {
            _isSnapping = true;
            try
            {
                await _board.TrySwapSingleGridAsync(_model, gridDelta.x, gridDelta.y);
            }
            finally
            {
                _isSnapping = false;
            }
        }

        private async UniTask DoGroupSwapAsync(Vector2Int gridDelta)
        {
            var group = _dragGroup;
            _isSnapping = true;
            _dragGroup = null;
            try
            {
                await _board.TrySwapGroupAsync(group, gridDelta.x, gridDelta.y);
            }
            finally
            {
                _isSnapping = false;
            }
        }

        private async UniTask SnapBackSingleAsync()
        {
            _isSnapping = true;
            Vector2 gridPos = _board.GetWorldPosition(_model.BoardCol, _model.BoardRow);
            var seq = DOTween.Sequence();
            seq.Append(transform.DOMove(gridPos, snapDuration).SetEase(Ease.Linear));
            await seq.AsyncWaitForCompletion();
            _dragGroup = null;
            _isSnapping = false;
        }

        /// <summary>Snaps the group back to its original position before the drag started.</summary>
        private async UniTask SnapBackGroupAsync()
        {
            if (_dragGroup == null) return;
            _isSnapping = true;

            if (_dragGroup.GroupTransform != null)
            {
                await _dragGroup.GroupTransform
                    .DOMove(_groupDragOriginPos, snapDuration)
                    .SetEase(Ease.OutCubic)
                    .AsyncWaitForCompletion();
            }

            _isSnapping = false;
            _dragGroup = null;
        }

        #endregion

        #region Effects

        public void PlayRippleEffect(float delay)
        {
            if (_model == null) return;

            var seq = DOTween.Sequence();
            seq.SetDelay(delay);
            seq.Append(transform.DOScale(Vector3.one * RippleScaleUp, RippleScaleUpDuration).SetEase(Ease.Linear));
            seq.Append(transform.DOScale(Vector3.one, RippleScaleDownDuration).SetEase(Ease.OutQuad))
                .OnComplete(() => transform.localScale = Vector3.one);
        }

        #endregion

        #region Private Helpers

        private Transform GetDragTransform()
        {
            return _dragGroup != null && _dragGroup.GroupTransform != null
                ? _dragGroup.GroupTransform
                : transform;
        }

        private Vector3 ScreenToWorld(Vector2 screenPosition)
        {
            if (_mainCamera == null)
                _mainCamera = Camera.main;

            if (_mainCamera == null)
                return transform.position;

            Vector3 worldPosition = _mainCamera.ScreenToWorldPoint(screenPosition);
            worldPosition.z = _board != null ? _board.transform.position.z : 0f;
            return worldPosition;
        }

        private void ForceCompletePendingTweens()
        {
            if (_model.Group != null)
            {
                foreach (var member in _model.Group.Members)
                {
                    var view = _board.cardFactory.GetView(member.TileId);
                    if (view != null) view.transform.DOComplete();
                }
            }
            else
            {
                transform.DOComplete();
            }
        }

        private void BeginGroupDrag(Vector3 mouseWorldPos)
        {
            _groupDragOriginPos = _dragGroup.GroupTransform.position;
            _dragGroup.GroupTransform.DOScale(liftScale, liftDuration).SetEase(Ease.OutBack);

            // The group parent is movement-only. Raise each card's own SortingGroup so bridge
            // renderers remain independent and cannot cover cards belonging to other groups.
            foreach (var member in _dragGroup.Members)
            {
                if (member == null) continue;
                var view = _board.cardFactory.GetView(member.TileId);
                if (view != null)
                    view.SetSortingOrder(dragSortingOrder);
            }

            _dragOffset = _dragGroup.GroupTransform.position - mouseWorldPos;
        }

        private void SetGroupPressEffects(bool active)
        {
            if (_dragGroup == null || _board == null || _board.cardFactory == null) return;

            foreach (var member in _dragGroup.Members)
            {
                if (member == null) continue;

                var view = _board.cardFactory.GetView(member.TileId);
                if (view != null && view.pressEffect != null)
                    view.pressEffect.SetActive(active);
            }
        }

        private void BeginSingleDrag(Vector3 mouseWorldPos)
        {
            _dragOffset = transform.position - mouseWorldPos;
            SetSortingOrder(dragSortingOrder);
            transform.DOScale(liftScale, liftDuration).SetEase(Ease.OutBack);
        }

        private async UniTask HandleGroupRelease()
        {
            var gridDelta = CalculateGroupGridDelta();
            var memberViews = new List<CardView>();
            if (_dragGroup != null)
            {
                foreach (var member in _dragGroup.Members)
                {
                    if (member == null) continue;
                    var view = _board.cardFactory.GetView(member.TileId);
                    if (view != null) memberViews.Add(view);
                }
            }

            _dragGroup?.GroupTransform.DOKill(true);

            // Reset scale immediately to prevent gaps between cards
            if (_dragGroup?.GroupTransform != null)
                _dragGroup.GroupTransform.localScale = Vector3.one;

            _dragGroup?.GroupTransform.DORotateQuaternion(Quaternion.identity, snapDuration).SetEase(Ease.OutBack);

            try
            {
                if (gridDelta.x != 0 || gridDelta.y != 0)
                    await DoGroupSwapAsync(gridDelta);
                else
                    await SnapBackGroupAsync();
            }
            finally
            {
                // RebuildGroups can replace the CardGroup and clear _dragGroup during the await,
                // so restore cached views even if settlement or a UI callback throws.
                foreach (var view in memberViews)
                {
                    SnapViewToCurrentGridImmediate(view);
                    if (view != null) view.SetSortingOrder(view.baseSortingOrder);
                }
                _dragGroup = null;
            }
        }

        private void OnDisable()
        {
            _backgroundColorTween?.Kill();
            _backgroundColorTween = null;
            _isDragging = false;
            _isSnapping = false;
            _releaseInProgress = false;
            _activePointerId = NoPointer;
            if (_activeDragView == this)
                _activeDragView = null;
        }

        private async UniTask HandleSingleRelease()
        {
            transform.DOScale(1f, snapDuration);
            transform.DORotateQuaternion(Quaternion.identity, snapDuration).SetEase(Ease.OutBack);

            var gridDelta = CalculateSingleGridDelta();

            try
            {
                if (gridDelta.x != 0 || gridDelta.y != 0)
                    await DoSingleGridSwapAsync(gridDelta);
                else
                    await SnapBackSingleAsync();
            }
            finally
            {
                SnapViewToCurrentGridImmediate(this);
                SetSortingOrder(baseSortingOrder);
                _dragGroup = null;
            }
        }

        private void SnapViewToCurrentGridImmediate(CardView view)
        {
            if (view == null || view.Model == null || _board == null ||
                !view.gameObject.activeInHierarchy)
                return;

            view.transform.DOKill();
            view.transform.position = _board.GetWorldPosition(
                view.Model.BoardCol,
                view.Model.BoardRow);
            view.transform.localScale = Vector3.one;
            view.transform.rotation = Quaternion.identity;

            // Force-snapping kills any board DOMove before its OnComplete callback can run.
            // Clear this explicitly or IsColumnBusy will permanently lock the card's column.
            view.Model.IsAnimating = false;
        }

        /// <summary>Calculates the grid delta for a group based on parent transform offset.</summary>
        private Vector2Int CalculateGroupGridDelta()
        {
            if (_dragGroup == null || _dragGroup.GroupTransform == null) return Vector2Int.zero;

            var config = GameManager.Instance.GameConfig;
            Vector2 worldDelta = (Vector2)_dragTargetPosition - _groupDragOriginPos;
            float strideX = config.cardWidth + config.cardGap;
            float strideY = config.cardHeight + config.cardGap;

            int deltaCol = Mathf.RoundToInt(worldDelta.x / strideX);
            int deltaRow = -Mathf.RoundToInt(worldDelta.y / strideY);

            return new Vector2Int(deltaCol, deltaRow);
        }

        /// <summary>Calculates the grid delta for a single tile drag.</summary>
        private Vector2Int CalculateSingleGridDelta()
        {
            var config = GameManager.Instance.GameConfig;
            Vector2 worldDelta = (Vector2)_dragTargetPosition - _originPos;
            float strideX = config.cardWidth + config.cardGap;
            float strideY = config.cardHeight + config.cardGap;

            int deltaCol = Mathf.RoundToInt(worldDelta.x / strideX);
            int deltaRow = -Mathf.RoundToInt(worldDelta.y / strideY);

            return new Vector2Int(deltaCol, deltaRow);
        }

        #endregion
    }
}
